import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  getStarted: [{ type: "autogenerated", dirName: "." }],
  mySidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "introduction",
          label: "Introduction",
        },
        {
          type: "doc",
          id: "architecture",
          label: "Protocol Overview",
        },
        {
          type: "doc",
          id: "usecases",
          label: "Usecases",
        },
      ],
    },
    {
      type: "category",
      label: "Building on SOCKET",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "getting-started",
          label: "Getting Started",
        },
        {
          type: "doc",
          id: "writing-apps",
          label: "Build chain abstracted apps",
        },
        {
          type: "doc",
          id: "call-onchain-from-evmx",
          label: "Call onchain from EVMx",
        },
        {
          type: "doc",
          id: "read-onchain-from-evmx",
          label: "Read onchain from EVMx",
        },
        {
          type: "doc",
          id: "trigger-appgateway-onchain",
          label: "Trigger AppGateway from onchain",
        },
        {
          type: "link",
          label: "Upload onchain contracts to EVMx",
          href: "/forwarder-addresses#uploading-an-onchain-contract-to-use-on-the-evmx-contract",
        },
        {
          type: "doc",
          id: "schedule",
          label: "Schedule EVMx execution",
        },
        {
          type: "doc",
          id: "write-tests",
          label: "Write tests for an AppGateway",
        },
        {
          type: "doc",
          id: "deploy",
          label: "Deploy contracts onchain",
        },
        {
          type: "doc",
          id: "fees",
          label: "Pay for your onchain transactions",
        },
        {
          type: "doc",
          id: "evmx",
          label: "EVMx Information",
        },
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "forwarder-addresses",
          label: "Forwarder Addresses",
        },
        {
          type: "doc",
          id: "promises",
          label: "Promises",
        },
        {
          type: "doc",
          id: "switchboards",
          label: "Switchboards",
        },
        {
          type: "doc",
          id: "transmitters",
          label: "Transmitters",
        },
        {
          type: "doc",
          id: "watchers",
          label: "Watchers",
        },
        {
          type: "doc",
          id: "glossary",
          label: "Glossary",
        },
      ],
    },
    {
      type: "category", 
      label: "Tools",
      link: {type: 'doc', id: 'tools'},
      collapsed: false,
      items: [
        {
          type: "category",
          label: "API Reference",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "api-reference",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "deployments",
          label: "Deployments",
        },
      ],
    },
    {
      type: "link",
      label: "Brand Assets",
      href: "https://www.figma.com/file/qwHGtazqA8qLGGj6TYpBu3/SOCKET-Brand-Assets",
    },
  ],
};

export default sidebars;
