import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  getStarted: [{ type: "autogenerated", dirName: "." }],
  mySidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "introduction",
          label: "What is SOCKET Protocol?",
        },
        {
          type: "doc",
          id: "architecture",
          label: "Learn how SOCKET works",
        },
        {
          type: "doc",
          id: "getting-started",
          label: "Getting Started",
        },
      ],
    },
    {
      type: "category",
      label: "Usecases",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "usecases",
          label: "Key Use Cases",
        },
        {
          type: "doc",
          id: "magicspend",
          label: "MagicSpend on SOCKET",
        },
        {
          type: "doc",
          id: "eip7683",
          label: "Multi-chain intents on SOCKET",
        },
      ],
    },
    {
      type: "category",
      label: "Building on SOCKET",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "writing-apps",
          label: "Build chain abstracted apps",
        },
        {
          type: "doc",
          id: "call-onchain-from-evmx",
          label: "Call onchain from EVMx",
        },
        {
          type: "doc",
          id: "read",
          label: "Read onchain",
        },
        {
          type: "doc",
          id: "deploy",
          label: "Deploy contracts onchain",
        },
        {
          type: "doc",
          id: "fees",
          label: "Pay for your transactions",
        },
        {
          type: "doc",
          id: "onchain-to-evmx",
          label: "Trigger AppGateway from onchain",
        },
        {
          type: "doc",
          id: "schedule",
          label: "Schedule EVMx execution",
        },
        {
          type: "doc",
          id: "write-tests",
          label: "Write tests for your app",
        },
        {
          type: "doc",
          id: "api",
          label: "API",
        },
        {
          type: "doc",
          id: "evmx",
          label: "EVMx Information",
        },
      ],
    },
    {
      type: "category",
      label: "Learn about SOCKET",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "forwarder-addresses",
          label: "Forwarder Addresses",
        },
        {
          type: "doc",
          id: "promises",
          label: "Promises",
        },
        {
          type: "doc",
          id: "switchboards",
          label: "Switchboards",
        },
        {
          type: "doc",
          id: "transmitters",
          label: "Transmitters",
        },
        {
          type: "doc",
          id: "watchers",
          label: "Watchers",
        },
        {
          type: "link",
          href: "https://media.socket.tech/SocketProtocol_v1.pdf",
          label: "Whitepaper",
        },
      ],
    },
    {
      type: "link",
      href: "https://sockettech.notion.site/SOCKET-Brand-Kit-184818fd285880b3b974e2e957cd70bd",
      label: "Brand Assets",
    },
  ],
};

export default sidebars;
