export const chainDetails = {
  1: {
    chainSlug: 1,
    chainName: "Ethereum",
    blockExplorerUrl: "https://etherscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Ether.svg",
  },
  5: {
    chainSlug: 5,
    chainName: "Goerli",
    blockExplorerUrl: "https://goerli.etherscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Ether.svg",
  },
  10: {
    chainSlug: 10,
    chainName: "Optimism",
    blockExplorerUrl: "https://optimistic.etherscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Optimism.svg",
  },
  56: {
    chainSlug: 56,
    chainName: "BNB Chain",
    blockExplorerUrl: "https://bscscan.com",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/BSC.svg",
  },
  89: {
    chainSlug: 89,
    chainName: "Viction testnet",
    blockExplorerUrl: "https://testnet.tomoscan.io",
    logoURI: "",
  },
  137: {
    chainSlug: 137,
    chainName: "Polygon",
    blockExplorerUrl: "https://polygonscan.com",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Matic.svg",
  },
  420: {
    chainSlug: 420,
    chainName: "Optimism Goerli",
    blockExplorerUrl: "https://goerli-optimism.etherscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Optimism.svg",
  },
  647: {
    chainSlug: 647,
    chainName: "Stavanger testnet",
    blockExplorerUrl: "https://sn2-stavanger-blockscout.eu-north-2.gateway.fm",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Matic.svg",
  },
  901: {
    chainSlug: 901,
    chainName: "Lyra testnet",
    blockExplorerUrl: "https://explorerl2new-prod-testnet-0eakp60405.t.conduit.xyz",
    logoURI: "/img/lyra-logo.png",
  },
  919: {
    chainSlug: 919,
    chainName: "Mode testnet",
    blockExplorerUrl: "https://sepolia.explorer.mode.network",
    logoURI: "",
  },
  957: {
    chainSlug: 957,
    chainName: "Lyra",
    blockExplorerUrl: "https://explorer.lyra.finance",
    logoURI: "/img/lyra-logo.png",
  },
  2999: {
    chainSlug: 2999,
    chainName: "Aevo",
    blockExplorerUrl: "https://explorer.aevo.xyz",
    logoURI: "/img/aevo-logo.png",
  },
  8453: {
    chainSlug: 8453,
    chainName: "Base",
    blockExplorerUrl: "https://basescan.org",
    logoURI: "https://media.socket.tech/Base.png",
  },
  34443: {
    chainSlug: 34443,
    chainName: "Mode",
    blockExplorerUrl: "https://explorer.mode.network",
    logoURI: "",
  },
  42161: {
    chainSlug: 42161,
    chainName: "Arbitrum",
    blockExplorerUrl: "https://arbiscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Arbitrum.svg",
  },
  80001: {
    chainSlug: 80001,
    chainName: "Polygon Mumbai testnet",
    blockExplorerUrl: "https://mumbai.polygonscan.com",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Matic.svg",
  },
  421613: {
    chainSlug: 421613,
    chainName: "Arbitrum Goerli",
    blockExplorerUrl: "https://goerli.arbiscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Arbitrum.svg",
  },
  421614: {
    chainSlug: 421614,
    chainName: "Arbitrum Sepolia",
    blockExplorerUrl: "https://sepolia.arbiscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Arbitrum.svg",
  },
  11155111: {
    chainSlug: 11155111,
    chainName: "Sepolia",
    blockExplorerUrl: "https://sepolia.etherscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Ether.svg",
  },
  11155112: {
    chainSlug: 11155112,
    chainName: "Aevo testnet",
    blockExplorerUrl: "https://explorer-testnet.aevo.xyz",
    logoURI: "/img/aevo-logo.png",
  },
  11155420: {
    chainSlug: 11155420,
    chainName: "Optimism Sepolia",
    blockExplorerUrl: "https://sepolia-optimism.etherscan.io",
    logoURI: "https://movricons.s3.ap-south-1.amazonaws.com/Optimism.svg",
  },
  686669576: {
    chainSlug: 686669576,
    chainName: "SX Network Testnet",
    blockExplorerUrl: "https://explorer.toronto.sx.technology",
    logoURI: "/img/sx-logo.png",
  },
  1399904803: {
    chainSlug: 1399904803,
    chainName: "XAI Testnet",
    blockExplorerUrl: "https://testnet-explorer.xai-chain.net",
    logoURI: "/img/xai-logo.png",
  },
};
